tasks:
  - name: HCS chat demo
    before: cp -n .env.sample .env
    init: yarn
#    command: yarn run serve --host 0.0.0.0 --disable-host-check
    command: node server.js

ports:
  - port: 8080
    onOpen: open-preview